/**
 * Error codes for subscriptions domain.
 * Follows the pattern in src/domain/common/errors.ts
 */

export const SubscriptionErrorCodes = {
    SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
    SUBSCRIPTION_ALREADY_EXISTS: 'SUBSCRIPTION_ALREADY_EXISTS',
    SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
    SUBSCRIPTION_ACCESS_DENIED: 'SUBSCRIPTION_ACCESS_DENIED',
    INVALID_STATUS_TRANSITION: 'SUBSCRIPTION_INVALID_STATUS_TRANSITION',
    PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
    TRIAL_LINK_NOT_FOUND: 'TRIAL_LINK_NOT_FOUND',
    TRIAL_LINK_EXPIRED: 'TRIAL_LINK_EXPIRED',
    TRIAL_LINK_EXHAUSTED: 'TRIAL_LINK_EXHAUSTED',
    TRIAL_LINK_INACTIVE: 'TRIAL_LINK_INACTIVE',
    TRIAL_LINK_CODE_CONFLICT: 'TRIAL_LINK_CODE_CONFLICT',
    PAYMENT_EVENT_DUPLICATE: 'PAYMENT_EVENT_DUPLICATE',
    PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
    CHECKOUT_SESSION_FAILED: 'CHECKOUT_SESSION_FAILED'
} as const
