#!/usr/bin/env tsx
/**
 * Setup Test Environment
 *
 * Este script:
 * 1. Verifica que Supabase local esté corriendo
 * 2. Obtiene las variables de entorno desde supabase status
 * 3. Crea/actualiza .env.test con las credenciales locales
 * 4. Aplica migraciones de Prisma a la DB local
 */

import { execSync } from 'child_process'
import { writeFileSync } from 'fs'
import path from 'path'

function execCommand(command: string): string {
    try {
        return execSync(command, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] })
    } catch (error) {
        if (error instanceof Error && 'stdout' in error) {
            return (error as { stdout: string }).stdout
        }
        throw error
    }
}

async function setupTestEnvironment() {
    console.log('🔧 Setting up test environment...\n')

    // 1. Check if Supabase is running
    console.log('1️⃣  Checking Supabase local status...')
    try {
        const status = execCommand('npx supabase status')
        if (!status.includes('API URL')) {
            throw new Error('Supabase not running properly')
        }
        console.log('✅ Supabase local is running\n')
    } catch {
        console.log('❌ Supabase local not running. Starting...')
        execSync('npx supabase start', { stdio: 'inherit' })
        console.log('✅ Supabase local started\n')
    }

    // 2. Parse Supabase status to get credentials
    console.log('2️⃣  Parsing Supabase credentials...')
    const statusJson = execCommand('npx supabase status --output json')
    const status = JSON.parse(statusJson)

    const apiUrl = status.API_URL
    const dbUrl = status.DB_URL
    const anonKey = status.ANON_KEY
    const serviceRoleKey = status.SERVICE_ROLE_KEY

    if (!apiUrl || !dbUrl || !anonKey || !serviceRoleKey) {
        throw new Error('Could not parse Supabase credentials from status output')
    }

    console.log('✅ Credentials parsed\n')

    // 3. Create .env.test file
    console.log('3️⃣  Creating .env.test file...')
    const envTestContent = `# Auto-generated by setup-test-env.ts
# DO NOT COMMIT THIS FILE

# Supabase Local
NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${anonKey}
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}

# Database (Supabase local)
DATABASE_URL=${dbUrl}
    DIRECT_DATABASE_URL=${dbUrl}

# Next.js
NEXT_PUBLIC_APP_URL=http://localhost:3000
    # Disable rate limits for automated tests
    DISABLE_RATE_LIMIT=true
`

    const envTestPath = path.join(process.cwd(), '.env.test')
    writeFileSync(envTestPath, envTestContent)
    console.log(`✅ Created ${envTestPath}\n`)

    // 4. Apply Prisma migrations to local DB
    console.log('4️⃣  Applying Prisma migrations...')
    try {
        execSync('npx dotenv -e .env.test -- npx prisma migrate deploy', {
            stdio: 'inherit',
            env: { ...process.env, DATABASE_URL: dbUrl }
        })
        console.log('✅ Migrations applied\n')
    } catch (error) {
        console.error('⚠️  Error applying migrations:', error)
        console.log('Continuing anyway...\n')
    }

    // 5. Generate Prisma client
    console.log('5️⃣  Generating Prisma client...')
    execSync('npx prisma generate', { stdio: 'inherit' })
    console.log('✅ Prisma client generated\n')

    console.log('✅ Test environment ready!')
    console.log(`
📝 Next steps:
   - Run unit tests: yarn test
   - Run E2E tests: yarn e2e
   - Reset test DB: yarn test:reset-db
`)
}

setupTestEnvironment().catch(error => {
    console.error('❌ Setup failed:', error)
    process.exit(1)
})
